/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;
import Conexion.ConexionBD;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author danie
 */
public class JFrameMultas extends javax.swing.JFrame {

    ConexionBD conn = new ConexionBD();
    Connection C = conn.conexion();
    
    /**
     *
     */
    public JFrameMultas() {
        initComponents();
        this.LlenarComboBoxInfracciones(InfraccionMulta);
        this.LlenarComboBoxInfracciones(ModCBMultas);
        MostrarTablaMultasPersona(TablaMultaPersona,ConsultaMultaCodUsu);
        MostrarTablaMultasPersona(TablaMultasModificacion,ConsultaMultaCodUsu1);
        MostrarTablaMultasPersona(TablaMultasModificacion1,ConsultaMultaCodUsu2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        RegistroMultas = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        MultasCodPersona = new javax.swing.JTextField();
        BotonBuscarPersonaMultas = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        MultasNomPersona = new javax.swing.JTextField();
        MultasApePersona = new javax.swing.JTextField();
        MultasFechaNacPersona = new javax.swing.JTextField();
        MultasDireccionPesona = new javax.swing.JTextField();
        MultasCiudadPersona = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        ArticuloMulta = new javax.swing.JTextField();
        LugarMulta = new javax.swing.JTextField();
        ImporteMulta = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        MultaMatricula = new javax.swing.JTextField();
        MultaMarca = new javax.swing.JTextField();
        MultaModelo = new javax.swing.JTextField();
        BotonBuscarVehiculoMultas = new javax.swing.JButton();
        BotonGuardarMulta = new javax.swing.JButton();
        LimpiarCampos = new javax.swing.JButton();
        InfraccionMulta = new javax.swing.JComboBox<>();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        MultasCodAgente = new javax.swing.JTextField();
        MultasNomAgente = new javax.swing.JTextField();
        MultasApellidosAgente = new javax.swing.JTextField();
        MultasTelAgente = new javax.swing.JTextField();
        BotonBuscarAgenteMultas = new javax.swing.JButton();
        ConsultaMultas = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaMultaPersona = new javax.swing.JTable();
        jLabel19 = new javax.swing.JLabel();
        ConsultaMultaCodUsu = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        ConsultaMultaNomUsu = new javax.swing.JTextField();
        ConsultaMultaApellidosUsu = new javax.swing.JTextField();
        ConsultaMultasFechaNacPersona = new javax.swing.JTextField();
        ConsultaMultasDireccionPesona = new javax.swing.JTextField();
        ConsultaMultasCiudadPersona = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        BotonConsultaPersona = new javax.swing.JButton();
        ModificarMulta = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaMultasModificacion = new javax.swing.JTable();
        jLabel35 = new javax.swing.JLabel();
        ConsultaMultaCodUsu1 = new javax.swing.JTextField();
        BotonConsultaPersona1 = new javax.swing.JButton();
        BotonModificarMulta = new javax.swing.JButton();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        ModImporte = new javax.swing.JTextField();
        ModArticulo = new javax.swing.JTextField();
        ModFechaChooser = new com.toedter.calendar.JDateChooser();
        ModCBMultas = new javax.swing.JComboBox<>();
        ModLugar = new javax.swing.JTextField();
        GuardarActualizarMultas = new javax.swing.JButton();
        jLabel38 = new javax.swing.JLabel();
        ModCodMulta = new javax.swing.JTextField();
        EliminarMulta = new javax.swing.JPanel();
        jLabel40 = new javax.swing.JLabel();
        ConsultaMultaCodUsu2 = new javax.swing.JTextField();
        BotonConsultaPersona2 = new javax.swing.JButton();
        BotonEliminarMulta = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TablaMultasModificacion1 = new javax.swing.JTable();
        jLabel39 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        RegistroMultas.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 18))); // NOI18N

        jLabel2.setText("Numero identificación:");

        jLabel3.setText("Datos persona infractora");

        MultasCodPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasCodPersonaActionPerformed(evt);
            }
        });

        BotonBuscarPersonaMultas.setText("Buscar");
        BotonBuscarPersonaMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarPersonaMultasActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombres");

        jLabel5.setText("Apellidos");

        jLabel6.setText("Fecha Nacimiento");

        jLabel7.setText("Direccion");

        jLabel8.setText("Ciudad");

        MultasNomPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasNomPersonaActionPerformed(evt);
            }
        });

        MultasApePersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasApePersonaActionPerformed(evt);
            }
        });

        MultasFechaNacPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasFechaNacPersonaActionPerformed(evt);
            }
        });

        MultasDireccionPesona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasDireccionPesonaActionPerformed(evt);
            }
        });

        MultasCiudadPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasCiudadPersonaActionPerformed(evt);
            }
        });

        jLabel9.setText("Datos Multas");

        jLabel10.setText("Fecha:");

        jLabel11.setText("Articulo:");

        jLabel12.setText("Lugar:");

        jLabel13.setText("Importe:");

        jLabel14.setText("Infracción:");

        LugarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LugarMultaActionPerformed(evt);
            }
        });

        jLabel1.setText("Datos Vehiculo");

        jLabel15.setText("Matricula:");

        jLabel16.setText("Marca:");

        jLabel17.setText("Modelo:");

        MultaMarca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultaMarcaActionPerformed(evt);
            }
        });

        BotonBuscarVehiculoMultas.setText("Buscar");
        BotonBuscarVehiculoMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarVehiculoMultasActionPerformed(evt);
            }
        });

        BotonGuardarMulta.setText("Registrar");
        BotonGuardarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonGuardarMultaActionPerformed(evt);
            }
        });

        LimpiarCampos.setText("Limpiar");
        LimpiarCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarCamposActionPerformed(evt);
            }
        });

        InfraccionMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfraccionMultaActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-d");

        jLabel25.setText("Datos Agente");

        jLabel26.setText("Numero identificación:");

        jLabel27.setText("Nombres:");

        jLabel28.setText("Apellidos:");

        jLabel29.setText("Telefono:");

        MultasCodAgente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultasCodAgenteActionPerformed(evt);
            }
        });

        BotonBuscarAgenteMultas.setText("Buscar");
        BotonBuscarAgenteMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonBuscarAgenteMultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout RegistroMultasLayout = new javax.swing.GroupLayout(RegistroMultas);
        RegistroMultas.setLayout(RegistroMultasLayout);
        RegistroMultasLayout.setHorizontalGroup(
            RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MultasCodPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasNomPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasApePersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasFechaNacPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasDireccionPesona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasCiudadPersona, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonBuscarPersonaMultas)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(RegistroMultasLayout.createSequentialGroup()
                                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ImporteMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(LugarMulta, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(ArticuloMulta, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jDateChooser1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                                    .addComponent(InfraccionMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 488, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel9)))
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(RegistroMultasLayout.createSequentialGroup()
                                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel16)
                                            .addComponent(jLabel17)))
                                    .addComponent(jLabel15))
                                .addGap(18, 18, 18)
                                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                                        .addComponent(BotonGuardarMulta)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LimpiarCampos))
                                    .addComponent(MultaMatricula)
                                    .addComponent(MultaMarca)
                                    .addComponent(MultaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BotonBuscarVehiculoMultas)))
                        .addGap(18, 18, 18)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel27)
                            .addComponent(jLabel26)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel25))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(MultasNomAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasApellidosAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasCodAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(MultasTelAgente, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotonBuscarAgenteMultas)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        RegistroMultasLayout.setVerticalGroup(
            RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(RegistroMultasLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10)
                            .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(ArticuloMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(LugarMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(ImporteMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(InfraccionMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasCodPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscarPersonaMultas)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasNomPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasApePersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasFechaNacPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasDireccionPesona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(MultasCiudadPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(26, 26, 26)
                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(MultaMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscarVehiculoMultas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(MultaMarca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(MultaModelo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(RegistroMultasLayout.createSequentialGroup()
                        .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel26)
                            .addComponent(MultasCodAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BotonBuscarAgenteMultas))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27)
                            .addComponent(MultasNomAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel28)
                            .addComponent(MultasApellidosAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(MultasTelAgente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12)
                .addGroup(RegistroMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonGuardarMulta)
                    .addComponent(LimpiarCampos))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Registro de multas", RegistroMultas);

        jLabel18.setText("Consulta de multas por identificacion de persona");

        TablaMultaPersona.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(TablaMultaPersona);

        jLabel19.setText("Numero de documento:");

        ConsultaMultaCodUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultaCodUsuActionPerformed(evt);
            }
        });

        jLabel20.setText("Fecha Nacimiento:");

        jLabel21.setText("Direccion:");

        jLabel22.setText("Ciudad:");

        ConsultaMultaNomUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultaNomUsuActionPerformed(evt);
            }
        });

        ConsultaMultaApellidosUsu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultaApellidosUsuActionPerformed(evt);
            }
        });

        ConsultaMultasFechaNacPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultasFechaNacPersonaActionPerformed(evt);
            }
        });

        ConsultaMultasDireccionPesona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultasDireccionPesonaActionPerformed(evt);
            }
        });

        ConsultaMultasCiudadPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultasCiudadPersonaActionPerformed(evt);
            }
        });

        jLabel23.setText("Nombres:");

        jLabel24.setText("Apellidos:");

        BotonConsultaPersona.setText("Buscar");
        BotonConsultaPersona.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaPersonaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ConsultaMultasLayout = new javax.swing.GroupLayout(ConsultaMultas);
        ConsultaMultas.setLayout(ConsultaMultasLayout);
        ConsultaMultasLayout.setHorizontalGroup(
            ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addGroup(ConsultaMultasLayout.createSequentialGroup()
                        .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 304, Short.MAX_VALUE)
                            .addGroup(ConsultaMultasLayout.createSequentialGroup()
                                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel24)
                                    .addComponent(jLabel20)
                                    .addComponent(jLabel21)
                                    .addComponent(jLabel22)
                                    .addComponent(jLabel23)
                                    .addComponent(jLabel19))
                                .addGap(18, 18, 18)
                                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(ConsultaMultaApellidosUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(ConsultaMultasFechaNacPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(ConsultaMultasDireccionPesona, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(ConsultaMultaNomUsu, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(ConsultaMultasCiudadPersona, javax.swing.GroupLayout.DEFAULT_SIZE, 174, Short.MAX_VALUE)
                                    .addComponent(ConsultaMultaCodUsu))))
                        .addGap(18, 18, 18)
                        .addComponent(BotonConsultaPersona)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ConsultaMultasLayout.setVerticalGroup(
            ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ConsultaMultasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(ConsultaMultaCodUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonConsultaPersona))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMultaNomUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMultaApellidosUsu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMultasFechaNacPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMultasDireccionPesona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(ConsultaMultasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ConsultaMultasCiudadPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 260, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Consulta de multas", ConsultaMultas);

        jLabel33.setText("Consulta de multas por identificacion de persona");

        TablaMultasModificacion.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(TablaMultasModificacion);

        jLabel35.setText("Numero de documento:");

        ConsultaMultaCodUsu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultaCodUsu1ActionPerformed(evt);
            }
        });

        BotonConsultaPersona1.setText("Buscar");
        BotonConsultaPersona1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaPersona1ActionPerformed(evt);
            }
        });

        BotonModificarMulta.setText("Modificar");
        BotonModificarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonModificarMultaActionPerformed(evt);
            }
        });

        jLabel30.setText("Datos de la multa");

        jLabel31.setText("Fecha:");

        jLabel32.setText("Articulo:");

        jLabel34.setText("Importe:");

        jLabel36.setText("Infraccion:");

        jLabel37.setText("Lugar:");

        ModFechaChooser.setDateFormatString("yyyy-MM-d");

        ModLugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModLugarActionPerformed(evt);
            }
        });

        GuardarActualizarMultas.setText("Actualizar");
        GuardarActualizarMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GuardarActualizarMultasActionPerformed(evt);
            }
        });

        jLabel38.setText("Codigo multa:");

        ModCodMulta.setEnabled(false);

        javax.swing.GroupLayout ModificarMultaLayout = new javax.swing.GroupLayout(ModificarMulta);
        ModificarMulta.setLayout(ModificarMultaLayout);
        ModificarMultaLayout.setHorizontalGroup(
            ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarMultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addGroup(ModificarMultaLayout.createSequentialGroup()
                        .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(ModificarMultaLayout.createSequentialGroup()
                                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModificarMultaLayout.createSequentialGroup()
                                        .addComponent(jLabel35)
                                        .addGap(18, 18, 18)
                                        .addComponent(ConsultaMultaCodUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BotonConsultaPersona1)
                                .addGap(18, 18, 18)
                                .addComponent(BotonModificarMulta))
                            .addComponent(jLabel30)
                            .addGroup(ModificarMultaLayout.createSequentialGroup()
                                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel38)
                                    .addComponent(jLabel31, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel32, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel34, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel36, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel37, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(18, 18, 18)
                                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(ModificarMultaLayout.createSequentialGroup()
                                        .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(ModFechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ModArticulo)
                                            .addComponent(ModImporte)
                                            .addComponent(ModCBMultas, 0, 402, Short.MAX_VALUE)
                                            .addComponent(ModLugar))
                                        .addGap(18, 18, 18)
                                        .addComponent(GuardarActualizarMultas))
                                    .addComponent(ModCodMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        ModificarMultaLayout.setVerticalGroup(
            ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ModificarMultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(ConsultaMultaCodUsu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonConsultaPersona1)
                    .addComponent(BotonModificarMulta))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel38)
                    .addComponent(ModCodMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel31)
                    .addComponent(ModFechaChooser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ModArticulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(ModImporte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(GuardarActualizarMultas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(ModCBMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(ModificarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel37)
                    .addComponent(ModLugar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        jTabbedPane1.addTab("Modificar multa", ModificarMulta);

        jLabel40.setText("Consulta de multas por identificacion de persona");

        ConsultaMultaCodUsu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ConsultaMultaCodUsu2ActionPerformed(evt);
            }
        });

        BotonConsultaPersona2.setText("Buscar");
        BotonConsultaPersona2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonConsultaPersona2ActionPerformed(evt);
            }
        });

        BotonEliminarMulta.setText("Eliminar");
        BotonEliminarMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEliminarMultaActionPerformed(evt);
            }
        });

        TablaMultasModificacion1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane3.setViewportView(TablaMultasModificacion1);

        jLabel39.setText("Numero de documento:");

        javax.swing.GroupLayout EliminarMultaLayout = new javax.swing.GroupLayout(EliminarMulta);
        EliminarMulta.setLayout(EliminarMultaLayout);
        EliminarMultaLayout.setHorizontalGroup(
            EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarMultaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel40)
                    .addGroup(EliminarMultaLayout.createSequentialGroup()
                        .addComponent(jLabel39)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConsultaMultaCodUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotonConsultaPersona2)
                        .addGap(18, 18, 18)
                        .addComponent(BotonEliminarMulta)))
                .addContainerGap(495, Short.MAX_VALUE))
            .addGroup(EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EliminarMultaLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 951, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        EliminarMultaLayout.setVerticalGroup(
            EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EliminarMultaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel40)
                .addGap(18, 18, 18)
                .addGroup(EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel39)
                    .addComponent(ConsultaMultaCodUsu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BotonConsultaPersona2)
                    .addComponent(BotonEliminarMulta))
                .addContainerGap(405, Short.MAX_VALUE))
            .addGroup(EliminarMultaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(EliminarMultaLayout.createSequentialGroup()
                    .addGap(86, 86, 86)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(140, Short.MAX_VALUE)))
        );

        jTabbedPane1.addTab("Eliminar multa", EliminarMulta);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ConsultaMultaCodUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultaCodUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultaCodUsuActionPerformed

    private void ConsultaMultaNomUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultaNomUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultaNomUsuActionPerformed

    private void ConsultaMultaApellidosUsuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultaApellidosUsuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultaApellidosUsuActionPerformed

    private void ConsultaMultasFechaNacPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultasFechaNacPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultasFechaNacPersonaActionPerformed

    private void ConsultaMultasDireccionPesonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultasDireccionPesonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultasDireccionPesonaActionPerformed

    private void ConsultaMultasCiudadPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultasCiudadPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultasCiudadPersonaActionPerformed
    
   
    private void BotonConsultaPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaPersonaActionPerformed
        try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM propietario WHERE cod_propietario = '"+ConsultaMultaCodUsu.getText()+"'");

            if (rs.next())
            {
                ConsultaMultaNomUsu.setText(rs.getString("NOMBRE_PROPIETARIO"));
                ConsultaMultaApellidosUsu.setText(rs.getString("APELLIDO_PROPIETARIO"));
                ConsultaMultasDireccionPesona.setText(rs.getString("DIRECCION_PROPIETARIO"));
                ConsultaMultasFechaNacPersona.setText(rs.getString("FECHANAC_PROPIETARIO"));
                ResultSet rsciudad = stat.executeQuery("SELECT * FROM ciudades WHERE cod_ciudad = '"+rs.getString("COD_CIUDAD")+"'");
                while(rsciudad.next())
                {
                    ConsultaMultasCiudadPersona.setText(rsciudad.getString("NOMBRE_CIUDAD"));
                }
                MostrarTablaMultasPersona(TablaMultaPersona,ConsultaMultaCodUsu);
            }
            else{
                JOptionPane.showMessageDialog(null, "No se encontró");
            }

        } catch (SQLException ex)
        {
            //OcultaErrores
        }
    }//GEN-LAST:event_BotonConsultaPersonaActionPerformed

    private void BotonBuscarAgenteMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarAgenteMultasActionPerformed
        try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM agentes_transito WHERE cod_agente = '"+MultasCodAgente.getText()+"'");
            if (rs.next())
            {
                MultasNomAgente.setText(rs.getString("nombre_agente"));
                MultasApellidosAgente.setText(rs.getString("apellido_agente"));
                MultasTelAgente.setText(rs.getString("telefono_agente"));
            }
            else{
                JOptionPane.showMessageDialog(null, "No se encontró");
            }

        } catch (SQLException ex)
        {
            //OcultaErrores
        }
    }//GEN-LAST:event_BotonBuscarAgenteMultasActionPerformed

    private void MultasCodAgenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasCodAgenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasCodAgenteActionPerformed

    private void InfraccionMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfraccionMultaActionPerformed

    }//GEN-LAST:event_InfraccionMultaActionPerformed

    private void BotonBuscarVehiculoMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarVehiculoMultasActionPerformed
        try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM vehiculo WHERE cod_vehiculo = '"+MultaMatricula.getText()+"'");

            if (rs.next())
            {
                ResultSet rsmodelo = stat.executeQuery("SELECT * FROM modelos_autos WHERE cod_modelo = "+rs.getString("cod_modelo"));
                if(rsmodelo.next())
                {
                    MultaModelo.setText(rsmodelo.getString("nombre_modelo"));

                }
                ResultSet rsmarca = stat.executeQuery("SELECT * FROM marcas_autos WHERE cod_marca = "+rsmodelo.getString("cod_marca"));
                if(rsmarca.next())
                {
                    MultaMarca.setText(rsmarca.getString("nombre_marca"));
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se encontró");
            }

        } catch (SQLException ex)
        {
            //OcultaErrores
        }
    }//GEN-LAST:event_BotonBuscarVehiculoMultasActionPerformed

    private void MultaMarcaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultaMarcaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultaMarcaActionPerformed

    private void LugarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LugarMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LugarMultaActionPerformed

    private void MultasCiudadPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasCiudadPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasCiudadPersonaActionPerformed

    private void MultasDireccionPesonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasDireccionPesonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasDireccionPesonaActionPerformed

    private void MultasFechaNacPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasFechaNacPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasFechaNacPersonaActionPerformed

    private void MultasApePersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasApePersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasApePersonaActionPerformed

    private void MultasNomPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasNomPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasNomPersonaActionPerformed

    private void BotonBuscarPersonaMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonBuscarPersonaMultasActionPerformed
        try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM propietario WHERE cod_propietario = '"+MultasCodPersona.getText()+"'");

            if (rs.next())
            {
                MultasNomPersona.setText(rs.getString("NOMBRE_PROPIETARIO"));
                MultasApePersona.setText(rs.getString("APELLIDO_PROPIETARIO"));
                MultasDireccionPesona.setText(rs.getString("DIRECCION_PROPIETARIO"));
                MultasFechaNacPersona.setText(rs.getString("FECHANAC_PROPIETARIO"));
                MultasFechaNacPersona.setText(rs.getString("FECHANAC_PROPIETARIO"));
                ResultSet rsciudad = stat.executeQuery("SELECT * FROM ciudades WHERE cod_ciudad = '"+rs.getString("COD_CIUDAD")+"'");
                while(rsciudad.next())
                {
                    MultasCiudadPersona.setText(rsciudad.getString("NOMBRE_CIUDAD"));
                }
            }
            else{
                JOptionPane.showMessageDialog(null, "No se encontró");
            }

        } catch (SQLException ex)
        {
            //OcultaErrores
        }
    }//GEN-LAST:event_BotonBuscarPersonaMultasActionPerformed

    private void MultasCodPersonaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultasCodPersonaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MultasCodPersonaActionPerformed

    private void BotonGuardarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonGuardarMultaActionPerformed
        try {
            PreparedStatement pps = C.prepareStatement("insert into multas(fecha_multa,articulo_multa,lugar_multa,importe_multa,cod_agente,cod_propietario,cod_infraccion) values(?,?,?,?,?,?,?)");
            java.util.Date utilDate = jDateChooser1.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            pps.setDate(1, sqlDate);
            pps.setString(2,ArticuloMulta.getText());
            pps.setString(3,LugarMulta.getText());
            pps.setString(4,ImporteMulta.getText());
            pps.setString(5,MultasCodAgente.getText());
            pps.setString(6,MultasCodPersona.getText());
            pps.setString(7, String.valueOf(getInfraccionValor((String)InfraccionMulta.getSelectedItem())));
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Multa Guardada Exitosamente");
            
        } catch (SQLException ex) {
            System.out.println(ex);
        }
        
        
       
    }//GEN-LAST:event_BotonGuardarMultaActionPerformed

    private void LimpiarCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarCamposActionPerformed
        //Limpiada de campos persona infractora
        MultasCodPersona.setText("");
        MultasNomPersona.setText("");
        MultasApePersona.setText("");
        MultasFechaNacPersona.setText("");
        MultasDireccionPesona.setText("");
        MultasCiudadPersona.setText("");
        //Limpiada de campos vehiculo
        MultaMatricula.setText("");
        MultaMarca.setText("");
        MultaModelo.setText("");
        //Limpiada de campos multa
        ArticuloMulta.setText("");
        LugarMulta.setText("");   
        ImporteMulta.setText("");
        //Limpiada de campos agente
        MultasCodAgente.setText("");
        MultasNomAgente.setText("");
        MultasApellidosAgente.setText("");
        MultasTelAgente.setText("");             
    }//GEN-LAST:event_LimpiarCamposActionPerformed

    private void ConsultaMultaCodUsu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultaCodUsu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultaCodUsu1ActionPerformed

    private void BotonConsultaPersona1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaPersona1ActionPerformed
        try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM propietario WHERE cod_propietario = '"+ConsultaMultaCodUsu1.getText()+"'");
            if(!(rs.next()))
            {
                JOptionPane.showMessageDialog(null, "No se encontró al usuario.");
                
            }
            else
            {
               MostrarTablaMultasPersona(TablaMultasModificacion,ConsultaMultaCodUsu1);   
            }
            
        } catch (SQLException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BotonConsultaPersona1ActionPerformed

    private void BotonModificarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonModificarMultaActionPerformed
        int fila = TablaMultasModificacion.getSelectedRow();
        if(fila>=0)
        {
            ModCodMulta.setText(TablaMultasModificacion.getValueAt(fila, 0).toString());
            ModArticulo.setText(TablaMultasModificacion.getValueAt(fila, 3).toString());
            ModImporte.setText(TablaMultasModificacion.getValueAt(fila, 5).toString());
            ModLugar.setText(TablaMultasModificacion.getValueAt(fila, 4).toString());            
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Multa no seleccionada.");
        }
    }//GEN-LAST:event_BotonModificarMultaActionPerformed

    private void GuardarActualizarMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarActualizarMultasActionPerformed
        try {
            java.util.Date utilDate = ModFechaChooser.getDate();
            java.sql.Date sqlDate = new java.sql.Date(utilDate.getTime());
            Integer cod = (getInfraccionValor((String)ModCBMultas.getSelectedItem()));
            PreparedStatement pps = C.prepareStatement("update multas set fecha_multa = '"+sqlDate+"'"
            + ", articulo_multa = '"+ModArticulo.getText()+"'"
            + ", importe_multa = '"+ModImporte.getText()+"'"
            + ", lugar_multa = '"+ModLugar.getText()+"'"
            + ", cod_infraccion = "+cod        
            + " where cod_multa = '"+ModCodMulta.getText()+"'");
            pps.executeUpdate();
            JOptionPane.showMessageDialog(null, "Actualizacion correcta.");
            MostrarTablaMultasPersona(TablaMultasModificacion,ConsultaMultaCodUsu1);
            ModCodMulta.setText("");
            ModArticulo.setText("");
            ModImporte.setText("");
            ModLugar.setText("");
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMultas.class.getName()).log(Level.SEVERE, null, ex);
        }    
    }//GEN-LAST:event_GuardarActualizarMultasActionPerformed

    private void ModLugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModLugarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModLugarActionPerformed

    private void ConsultaMultaCodUsu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ConsultaMultaCodUsu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ConsultaMultaCodUsu2ActionPerformed

    private void BotonConsultaPersona2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonConsultaPersona2ActionPerformed
         try
        {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM propietario WHERE cod_propietario = '"+ConsultaMultaCodUsu2.getText()+"'");
            if(!(rs.next()))
            {
                JOptionPane.showMessageDialog(null, "No se encontró al usuario.");
                
            }
            else
            {
               MostrarTablaMultasPersona(TablaMultasModificacion1,ConsultaMultaCodUsu2);   
            }
            
        } catch (SQLException ex)
        {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BotonConsultaPersona2ActionPerformed

    private void BotonEliminarMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEliminarMultaActionPerformed
        int fila = TablaMultasModificacion1.getSelectedRow();
        String valor=TablaMultasModificacion1.getValueAt(fila,0).toString();
        if(fila>=0)
        {
            try {
                PreparedStatement pps = C.prepareStatement("delete from multas where cod_multa = '"+valor+"'");
                pps.executeUpdate();
                JOptionPane.showMessageDialog(null, "Multa eliminada.");
                MostrarTablaMultasPersona(TablaMultasModificacion1,ConsultaMultaCodUsu2);
            } catch (SQLException ex) {
                //Logger.getLogger(JFrameMultas.class.getName()).log(Level.SEVERE, null, ex);
            }   
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Multa no seleccionada.");
        }
    }//GEN-LAST:event_BotonEliminarMultaActionPerformed
    
    public Integer getInfraccionValor(String nombre) throws SQLException{
        Statement stat = (Statement) conn.conexion().createStatement();
        ResultSet rs = stat.executeQuery("SELECT COD_INFRACCION FROM infracciones WHERE DESCRIPCION_INFRACCION = '"+nombre+"'");
        while(rs.next()){
            return rs.getInt("COD_INFRACCION");
        }
        return null;
    }
    private void LlenarComboBoxInfracciones(javax.swing.JComboBox<String> InfraccionMulta)
    {
        try {
            Statement stat = (Statement) conn.conexion().createStatement();
            ResultSet rs = stat.executeQuery("SELECT * FROM infracciones");
            while(rs.next())
            {
                InfraccionMulta.addItem(rs.getString("descripcion_infraccion"));
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMultas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    
    private void MostrarTablaMultasPersona(javax.swing.JTable TablaMultaPersona,javax.swing.JTextField ConsultaMultaCodUsu)
    {
        
        DefaultTableModel modelo = new DefaultTableModel()
        {
            @Override
            public boolean isCellEditable(int filas, int columnas) {
               if(columnas==7){
                   return true;
               }
               else
               {
                   return false;
               }
            }
          
        };
        modelo.addColumn("Codigo Multa");
        modelo.addColumn("Fecha");
        modelo.addColumn("Agente");
        modelo.addColumn("Articulo");
        modelo.addColumn("Lugar");
        modelo.addColumn("Importe");
        modelo.addColumn("Infraccion");
        

        TablaMultaPersona.setModel(modelo);
        Statement stat;
        String datos[] = new String[7];
        try {
             stat = (Statement) conn.conexion().createStatement();
             ResultSet rs = stat.executeQuery("SELECT * FROM MULTAS WHERE COD_PROPIETARIO = '"+ConsultaMultaCodUsu.getText()+"'");
             while(rs.next())
             {
                 datos[0] = rs.getString("cod_multa"); 
                 datos[1] = rs.getString("fecha_multa");
                 datos[2] = rs.getString("cod_agente");
                 datos[3] = rs.getString("articulo_multa");
                 datos[4] = rs.getString("lugar_multa");
                 datos[5] = rs.getString("importe_multa");
                 datos[6] = rs.getString("cod_infraccion");
                 modelo.addRow(datos);
             }
             TablaMultaPersona.setModel(modelo);
             
        } catch (SQLException ex) {
            Logger.getLogger(JFrameMultas.class.getName()).log(Level.SEVERE, null, ex);
        }
       
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrameMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrameMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrameMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrameMultas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrameMultas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArticuloMulta;
    private javax.swing.JButton BotonBuscarAgenteMultas;
    private javax.swing.JButton BotonBuscarPersonaMultas;
    private javax.swing.JButton BotonBuscarVehiculoMultas;
    private javax.swing.JButton BotonConsultaPersona;
    private javax.swing.JButton BotonConsultaPersona1;
    private javax.swing.JButton BotonConsultaPersona2;
    private javax.swing.JButton BotonEliminarMulta;
    private javax.swing.JButton BotonGuardarMulta;
    private javax.swing.JButton BotonModificarMulta;
    private javax.swing.JTextField ConsultaMultaApellidosUsu;
    private javax.swing.JTextField ConsultaMultaCodUsu;
    private javax.swing.JTextField ConsultaMultaCodUsu1;
    private javax.swing.JTextField ConsultaMultaCodUsu2;
    private javax.swing.JTextField ConsultaMultaNomUsu;
    private javax.swing.JPanel ConsultaMultas;
    private javax.swing.JTextField ConsultaMultasCiudadPersona;
    private javax.swing.JTextField ConsultaMultasDireccionPesona;
    private javax.swing.JTextField ConsultaMultasFechaNacPersona;
    private javax.swing.JPanel EliminarMulta;
    private javax.swing.JButton GuardarActualizarMultas;
    private javax.swing.JTextField ImporteMulta;
    private javax.swing.JComboBox<String> InfraccionMulta;
    private javax.swing.JButton LimpiarCampos;
    private javax.swing.JTextField LugarMulta;
    private javax.swing.JTextField ModArticulo;
    private javax.swing.JComboBox<String> ModCBMultas;
    private javax.swing.JTextField ModCodMulta;
    private com.toedter.calendar.JDateChooser ModFechaChooser;
    private javax.swing.JTextField ModImporte;
    private javax.swing.JTextField ModLugar;
    private javax.swing.JPanel ModificarMulta;
    private javax.swing.JTextField MultaMarca;
    private javax.swing.JTextField MultaMatricula;
    private javax.swing.JTextField MultaModelo;
    private javax.swing.JTextField MultasApePersona;
    private javax.swing.JTextField MultasApellidosAgente;
    private javax.swing.JTextField MultasCiudadPersona;
    private javax.swing.JTextField MultasCodAgente;
    private javax.swing.JTextField MultasCodPersona;
    private javax.swing.JTextField MultasDireccionPesona;
    private javax.swing.JTextField MultasFechaNacPersona;
    private javax.swing.JTextField MultasNomAgente;
    private javax.swing.JTextField MultasNomPersona;
    private javax.swing.JTextField MultasTelAgente;
    private javax.swing.JPanel RegistroMultas;
    private javax.swing.JTable TablaMultaPersona;
    private javax.swing.JTable TablaMultasModificacion;
    private javax.swing.JTable TablaMultasModificacion1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
