/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Conexion.ConexionBD;
import java.sql.Connection;

/**
 *
 * @author Felipe
 */
public class PantallaPrincipal extends javax.swing.JFrame {

    ConexionBD Con = new ConexionBD();
    Connection cn = Con.conexion();
    
    public PantallaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelTituloPP = new javax.swing.JLabel();
        BotonAccesoPersonasVehiculos = new javax.swing.JButton();
        BotonAccesoInfracciones = new javax.swing.JButton();
        BotonAccesoVehiculos = new javax.swing.JButton();
        BotonAccesoMultas = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Infracciones Y Multas");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LabelTituloPP.setBackground(new java.awt.Color(0, 0, 0));
        LabelTituloPP.setFont(new java.awt.Font("Copperplate Gothic Bold", 0, 48)); // NOI18N
        LabelTituloPP.setForeground(new java.awt.Color(255, 255, 255));
        LabelTituloPP.setText("TRANSITO APP");
        getContentPane().add(LabelTituloPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 400, 50));

        BotonAccesoPersonasVehiculos.setText("Personas");
        BotonAccesoPersonasVehiculos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotonAccesoPersonasVehiculosMouseClicked(evt);
            }
        });
        BotonAccesoPersonasVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoPersonasVehiculosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAccesoPersonasVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 120, 110));

        BotonAccesoInfracciones.setText("Infracciones");
        BotonAccesoInfracciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoInfraccionesActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAccesoInfracciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 120, 100));

        BotonAccesoVehiculos.setText("Vehiculos");
        BotonAccesoVehiculos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoVehiculosActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAccesoVehiculos, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, 120, 110));

        BotonAccesoMultas.setBackground(new java.awt.Color(255, 255, 255));
        BotonAccesoMultas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/IconoMulta.png"))); // NOI18N
        BotonAccesoMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAccesoMultasActionPerformed(evt);
            }
        });
        getContentPane().add(BotonAccesoMultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 120, 110));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel2.setText("Multas");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 280, -1, -1));

        jLabel3.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel3.setText("Infracciones");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 440, -1, -1));

        jLabel4.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel4.setText("Personas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 280, -1, -1));

        jLabel5.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 18)); // NOI18N
        jLabel5.setText("Vehiculos");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoInicio.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BotonAccesoVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoVehiculosActionPerformed
        JframeVehiculos VentanaVehiculos = new JframeVehiculos();
        VentanaVehiculos.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BotonAccesoVehiculosActionPerformed

    private void BotonAccesoMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoMultasActionPerformed
        JFrameMultas VentanaMultas = new JFrameMultas();
        VentanaMultas.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BotonAccesoMultasActionPerformed

    private void BotonAccesoPersonasVehiculosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoPersonasVehiculosActionPerformed
        JframePersonas VentanaPersonas = new JframePersonas();
        VentanaPersonas.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BotonAccesoPersonasVehiculosActionPerformed

    private void BotonAccesoInfraccionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAccesoInfraccionesActionPerformed
        JframeInfracciones VentanaInfracciones = new JframeInfracciones();
        VentanaInfracciones.setVisible(true);
        //this.setVisible(false);
    }//GEN-LAST:event_BotonAccesoInfraccionesActionPerformed

    private void BotonAccesoPersonasVehiculosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotonAccesoPersonasVehiculosMouseClicked
        // TODO add your handling code here:
        JframePersonas jframePersonas = new JframePersonas();
        jframePersonas.setVisible(true);
    }//GEN-LAST:event_BotonAccesoPersonasVehiculosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PantallaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PantallaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonAccesoInfracciones;
    private javax.swing.JButton BotonAccesoMultas;
    private javax.swing.JButton BotonAccesoPersonasVehiculos;
    private javax.swing.JButton BotonAccesoVehiculos;
    private javax.swing.JLabel LabelTituloPP;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
